name:                lens
version:             0.1.0.0
github:              "Sinha-Ujjawal/lens"
license:             BSD3
author:              "Ujjawal Sinha"
maintainer:          "ujjawalsinhacool16021998@gmail.com"
copyright:           "2021 Ujjawal Sinha"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Sinha-Ujjawal/lens#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lens-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens

tests:
  lens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens
